tasks:
  - name: Install needed packages
    apt:
        state: present
        pkg:
            - docker.io
            - docker-compose
    become: yes
  - name: Add user {{ user }} to docker group
    user:
        name: '{{ user }}'
        groups: docker
        append: yes
    become: yes
  - name: Activate docker service
    systemd:
        state: started
        enabled: yes
        name: docker
        become: yes
  # Official way of install docker
  # - name: Install needed packages
  #   apt:
  #       pkg:
  #           - apt-transport-https
  #           - ca-certificats
  #           - curl
  #           - gnupg-agent
  #           - software-properties-common
  #   become: yes
  # - name: Add Docker GPG apt Key
  #   apt_key:
  #     url: https://download.docker.com/linux/ubuntu/gpg
  #     state: present
  # - name: Add Docker Repository
  #   apt_repository:
  #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
  #     state: present
  # - name: Install docker packages
  #   apt:
  #       pkg:
  #           - docker-ce
  #           - docker-ce-cli
  #           - containerd.io
  #   become: yes
