---
- name: Add influxDB key (Debian)
  shell: wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  become: yes
  args:
      executable: /bin/bash
- name: Source /etc/os-release (Debian)
  shell: source /etc/os-release
  args:
      executable: /bin/bash
- name: Add influxDB repository (Debian)
  shell: echo "deb https://repos.influxdata.com/debian buster stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  become: yes
  args:
      executable: /bin/bash
