- name: Install .env file
  template:
    src: templates/env
    dest: ~/docker-compose/filebrowser/.env
- name: Create necessary files
  file:
    path: "{{ item }}"
    state: touch
  loop:
    - ~/docker-compose/filebrowser/.filebrowser.json
    - ~/docker-compose/filebrowser/filebrowser.db
- name: Run filebrowser with docker-compose
  community.docker.docker_compose:
    project_src: ~/docker-compose/filebrowser
  register: output
