- name: Install .env file
  template:
    src: templates/env
    dest: ~/docker-compose/watchtower/.env
- name: Run watchtower with docker-compose
  community.docker.docker_compose:
    project_src: ~/docker-compose/watchtower
  register: output
