- name: Install .env file
  template:
    src: templates/env
    dest: ~/docker-compose/searx/.env
- name: Run searx with docker-compose
  community.docker.docker_compose:
    project_src: ~/docker-compose/searx
  register: output
