- name: Install .env file
  template:
    src: templates/env_airsonic
    dest: ~/docker-compose/airsonic/.env
- name: Run airsonic with docker-compose
  community.docker.docker_compose:
    project_src: ~/docker-compose/airsonic
  register: output
