- name: Install .env file
  template:
    src: templates/env_boinc
    dest: ~/docker-compose/boinc/.env
- name: Delete old BOINC directory
  file:
    path: /opt/appdata/boinc
    state: absent
  become: yes
- name: Run boinc with docker-compose
  community.docker.docker_compose:
    project_src: ~/docker-compose/boinc
  register: output
- name: Connect to account manager
  command: "docker exec -it boinc boinccmd --join_acct_mgr {{ boinc_account_manager_url }} \"{{ boinc_account_manager_username }}\" {{ boinc_account_manager_password }}"
